import streamlit as st
import requests
import datetime

import sys

BASE_URL="http://localhost:8000"

st.set_page_config(
    page_title="🌍 Travel Planner Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("🌍 Travel Planner Application")

# initialise chat history
if "messages" not in st.session_state:
    st.session_state.messages=[]

# Display chat history
st.header("Let me know your desired destination, and I'll help you organize your travel plan")

# Chat input box at bottom
with st.form(key="query_form",clear_on_submit=True):
    user_input=st.text_input("User Input",placeholder="Plan a 5-day trip to your favorite destination")
    submit_button=st.form_submit_button("Create Itinerary")

if submit_button and user_input.strip():
    try:
        with st.spinner("Hold on, crafting your itinerary..."):
            payload={"question":user_input}
            response=requests.post(f"{BASE_URL}/query",json=payload)

        if response.status_code==200:
            answer=response.json().get("answer", "No answer returned.")
            markdown_content=f"""🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** VacayGenie Travel Agent
            ---
            {answer}
            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip."
            """
            st.markdown(markdown_content)
        else:
            st.error("Bot failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"
